### ISSUE TITLE
Write better tick label formatter for logit scale that produces 50% and 99.99% instead of 50.00 or 100%

### ISSUE THREAD

**Issue by corneliusroemer** [corneliusroemer/desh-data#2]
The current tick label formatter is a bad hack. We need something more robust that produces the following behaviour:
`1%,10%,50%,99.9%,99.999%` etc.

This is the current hack (from SO I think):
https://github.com/corneliusroemer/desh-data/blob/696469da1e402fc1d30a1740eed26ee4a8e18b80/scripts/omicron_plot.py#L84

The challenge is to display decimals only for trailing 9s but not for trailing zeros.

This might do the job, but not 100% sure: https://numpy.org/doc/stable/reference/generated/numpy.format_float_positional.html

@lenaschimmel interested?

Edit: `np.format_float_positional` does the job:
```
np.format_float_positional(1.000, trim='-') # 1
np.format_float_positional(99.99, trim='-') # 99.99
```

**Comment by lenaschimmel** [comment]
Ah, that's a nice solution. I came up with this, less elegant one: `str(100*y).rstrip("0").rstrip(".")`, in context:

```python
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda y, _: str(100*y).rstrip("0").rstrip(".") + '%'))
```

**Comment by corneliusroemer** [comment]
Went down a rabbit hole that includes submitting a fix PR to numpy and trying to get it to build from source but failing 👀 
https://github.com/numpy/numpy/issues/12441
